### ISSUE TITLE
Menu not working

### ISSUE THREAD

**Issue by ronnie173** [LavaLite/cms#262]
Every time I try to add a new menu getting server error

**Comment by georgemjohn** [comment]
Fixed

**Comment by iamkudam** [comment]
Hw did u fix the issue still having servor error on menus ...
